# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/folksforfairerfines/folksforfairerfines.github.io"

[social.params]
icon = "brand-github"

[[social]]
identifier = "google-forms"
name = "Our survey"
url = "https://forms.gle/9w33eiy8C3aBUWHi8"

[social.params]
icon = "clipboard"

[[social]]
identifier = "change.org"
name = "Our petition"
url = "https://www.change.org/p/reform-court-fines-to-support-fairness-for-all"

[social.params]
icon = "users-group"